# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77ca7778870bd9681b26c795426e922c0ce1e51238b4eeb088f2ac6915229f4d38022693fb2d5b6c01d804d56b5fba11feb8f969acca217a1e4b67c268b7dc3f

test:
  secret_key_base: d9d134aa11181031ac758e7158658421ca1f9481e96c92531fe4ac82b0aacd1dae6da10732dbc47bb86b6e48f54b7ef6258db3d05cdff8170f47f021a10cea0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
